"""Unit tests for the AI stock screener query compiler in webapp/gemini.py."""
from unittest.mock import MagicMock, patch
from datetime import date
import pytest
from webapp.gemini import parse_nlp_screener_query

def test_parse_nlp_screener_query_success():
    """Verify that parse_nlp_screener_query correctly initializes the client and returns clean SQL."""
    mock_response = MagicMock()
    mock_response.text = "SELECT s.ticker FROM snapshots s JOIN technical_metrics t ON s.ticker = t.ticker AND s.as_of_date = t.as_of_date WHERE s.as_of_date = '2026-06-26' AND s.layer = 'L2' ORDER BY s.arf DESC"
    
    with patch("google.genai.Client") as mock_client_cls:
        mock_client = MagicMock()
        mock_client_cls.return_value = mock_client
        mock_client.models.generate_content.return_value = mock_response
        
        sql = parse_nlp_screener_query("fake_key", "芯片题材", date(2026, 6, 26))
        
        # Verify the client was initialized with the key
        mock_client_cls.assert_called_once_with(api_key="fake_key")
        
        # Verify generate_content was called with the correct model and parameters
        mock_client.models.generate_content.assert_called_once()
        call_kwargs = mock_client.models.generate_content.call_args[1]
        
        assert call_kwargs["model"] == "gemini-2.5-flash"
        assert "User Screener Query: 芯片题材" in call_kwargs["contents"]
        assert "2026-06-26" in call_kwargs["contents"]
        assert sql == mock_response.text

def test_parse_nlp_screener_query_with_markdown_stripping():
    """Verify that any accidental markdown formatting generated by the model is correctly stripped."""
    mock_response = MagicMock()
    mock_response.text = "```sql\nSELECT * FROM snapshots;\n```"
    
    with patch("google.genai.Client") as mock_client_cls:
        mock_client = MagicMock()
        mock_client_cls.return_value = mock_client
        mock_client.models.generate_content.return_value = mock_response
        
        sql = parse_nlp_screener_query("fake_key", "some query", date(2026, 6, 26))
        assert sql == "SELECT * FROM snapshots;"

def test_parse_nlp_screener_query_invalid():
    """Verify that if the model returns a non-SQL explanation, it is treated as invalid."""
    mock_response = MagicMock()
    mock_response.text = "This is not a SQL query."
    
    with patch("google.genai.Client") as mock_client_cls:
        mock_client = MagicMock()
        mock_client_cls.return_value = mock_client
        mock_client.models.generate_content.return_value = mock_response
        
        sql = parse_nlp_screener_query("fake_key", "some query", date(2026, 6, 26))
        assert sql.startswith("-- Generated query was invalid:")
        assert "This is not a SQL query." in sql
